baseURL = "https://sergiops.xyz"
languageCode = "en"
DefaultContentLanguage = "en"
title = "Sergio Méndez Website"
theme = "anatole"
summarylength = 10
enableEmoji = true
enableRobotsTXT = true

# Enable Disqus
#disqusShortname = ""

# Google Analytics
googleAnalytics = "UA-189725686-1"

# Syntax highlighting
pygmentsUseClasses = true
pygmentsCodeFences = true
pygmentsCodefencesGuessSyntax = true

[params]
title = "I'm Sergio Méndez"
author = "Sergio Méndez"
copyright = "2020-2021"
description = "DevOps, Cloud Native, Speaker, CNCF Meetup organizer, Kubernetes CK{A,AD}"
profilePicture = "https://github.com/sergioarmgpl.png"
keywords = ""
favicon = "favicons/"
# example ["css/custom.css"]
customCss = []
# example ["js/custom.js"]
customJs = [] 
mainSections = ["talks"]
images = ["images/site-feature-image.png"]
doNotLoadAnimations = false
# Form Spree Contact Form
#contactFormAction = "https://formspree.io/f/your-form-hash-here"
# Google Site Verify
#googleSiteVerify = "ABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789"
# indexDateFormat = "Mon, Jan 2, 2006"
# listDateFormat = "Jan 2"
# singleDateFormat = "Mon, Jan 2, 2006"

[params.simpleAnalytics]
# enable = true
# customurl = "https://analytics.example.com"

## Math settings
[params.math]
enable = false  # options: true, false. Enable math support globally, default: false. You can always enable math on per page.
use = "katex"  # options: "katex", "mathjax". default is "katex".

## Social links
# use 'fab' when brand icons, use 'fas' when standard solid icons.
[[params.socialIcons]]
icon = "fab fa-linkedin"
title = "Linkedin"
url = "https://www.linkedin.com/in/sergioarmgpl/"

[[params.socialIcons]]
icon = "fab fa-twitter"
title = "Twitter"
url = "https://twitter.com/sergioarmgpl"

[[params.socialIcons]]
icon = "fab fa-github"
title = "GitHub"
url = "https://github.com/sergioarmgpl"

#[[params.socialIcons]]
#icon = "fab fa-instagram"
#title = "instagram"
#url = "https://www.instagram.com/"

[[params.socialIcons]]
icon = "fas fa-envelope"
title = "e-mail"
url = "mailto:sergioarm.gpl@gmail.com"

## Menu items

[menu]

  [[menu.main]]
  name = "Home"
  identifier = "home"
  weight = 100
  url = "/"

  [[menu.main]]
  name = "Timeline"
  identifier = "timeline"
  weight = 150
  url = "https://timeline.sergiops.xyz"

  [[menu.main]]
  name = "Blog"
  weight = 200
  identifier = "blog"
  url = "https://blog.sergiops.xyz"

  [[menu.main]]
  name = "Resume"
  weight = 300
  identifier = "resume"
  url = "/resume/"

  [[menu.main]]
  name = "Talks"
  weight = 500
  identifier = "talks"
  url = "/talks/"

  [[menu.main]]
  name = "Community"
  weight = 600
  identifier = "community"
  url = "/community/"

  [[menu.main]]
  name = "About"
  weight = 700
  identifier = "about"
  url = "/about/"

  [[menu.main]]
  name = "Contact & Meet"
  weight = 800
  identifier = "contact"
  url = "/contact/"
