baseURL = "https://sergiops.xyz"
languageCode = "en"
DefaultContentLanguage = "en"
title = "Sergio Méndez Website"
theme = "anatole"
summarylength = 10
enableEmoji = true
enableRobotsTXT = true

[math]
enable = false  # options: true, false. Enable math support globally, default: false. You can always enable math on per page.
use = "katex"  # options: "katex", "mathjax". default is "katex".

# Syntax highlighting
pygmentsUseClasses = true
pygmentsCodeFences = true
pygmentsCodefencesGuessSyntax = true

[params]
title = "I'm Sergio Méndez"
author = "Sergio Méndez"
copyright = "2020-2025"
description = "Speaker, {CNCF,ARM} Ambassador, Author, K8s, Edge"
profilePicture = "https://github.com/sergioarmgpl.png"
keywords = ""
favicon = "favicons/"
# example ["css/custom.css"]
customCss = []
# example ["js/custom.js"]
customJs = [] 
mainSections = [""]
images = ["images/site-feature-image.png"]
doNotLoadAnimations = false
# Form Spree Contact Form
#contactFormAction = "https://formspree.io/f/your-form-hash-here"
# Google Site Verify
#googleSiteVerify = "ABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789"
# indexDateFormat = "Mon, Jan 2, 2006"
# listDateFormat = "Jan 2"
# singleDateFormat = "Mon, Jan 2, 2006"

## Social links
# use 'fab' when brand icons, use 'fas' when standard solid icons.
[[params.socialIcons]]
icon = "fab fa-linkedin"
title = "Linkedin"
url = "https://www.linkedin.com/in/sergioarmgpl"

[[params.socialIcons]]
icon = "fab fa-twitter"
title = "Twitter"
url = "https://twitter.com/sergioarmgpl"

[[params.socialIcons]]
icon = "fab fa-github"
title = "GitHub"
url = "https://github.com/sergioarmgpl"

#[[params.socialIcons]]
#icon = "fab fa-instagram"
#title = "instagram"
#url = "https://www.instagram.com/"

[[params.socialIcons]]
icon = "fas fa-globe"
title = "Social Networks"
url = "https://linktr.ee/sergioarmgpl"

[[params.socialIcons]]
icon = "fas fa-phone"
title = "Schedule a call"
url = "https://calendly.com/sergioarmgpl/meeting"

[[params.socialIcons]]
icon = "fas fa-envelope"
title = "e-mail"
url = "mailto:sergioarm.gpl@gmail.com"

[menu]

  [[menu.main]]
  name = "Home"
  identifier = "home"
  weight = 100
  url = "/"

  [[menu.main]]
  name = "Posts+Contribs"
  weight = 300
  identifier = "blog"
#  url = "https://blog.sergiops.xyz"
#  url = "https://dev.to/sergioarmgpl"
  url = "/posts_contribs"

  [[menu.main]]
  name = "Talks"
  weight = 400
  identifier = "talks"
  url = "/talks/"

  #[[menu.main]]
  #name = "Contributions"
  #weight = 500
  #identifier = "contribs"
  #url = "/contribs/"

  [[menu.main]]
  name = "Github"
  weight = 600
  identifier = "github"
  url = "https://github.com/sergioarmgpl"
  
  [[menu.main]]
  name = "Resume"
  weight = 700
  identifier = "resume"
  url = "https://docs.google.com/document/d/1Uu_ttaJQ3xk_Yu1g4CNWIQXBK7kgqgjnf7LTRrE9pkc/export?format=pdf"

  [[menu.main]]
  name = "My Book"
  weight = 800
  identifier = "books"
  url = "/books/"

  [[menu.main]]
  name = "About"
  weight = 800
  identifier = "about"
  url = "/about/"

[services]
# Enable Disqus.Disqus.Shortname
#  [services.disqus]
#    #shortname = 'your-disqus-shortname'
# Google Analytics
  [services.googleAnalytics]
    ID = 'G-4RT9ZH2MBM'